language: java
sudo: required
os:
  - linux
  - osx
dist: trusty
install: 
    - pip install mkdocs
    - pip install mkdocs-material
script: 
  - chmod 777 gradlew
  - chmod 777 e2e/integration_tests.sh
  - chmod 777 deploy.sh
  - ./gradlew buildJar buildWar buildCli buildDoc && ./e2e/integration_tests.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
